export enum PropertyType {
	HYUNDAI = 'HYUNDAI',
	GENESIS = 'GENESIS',
	BMW = 'BMW',
	KIA = 'KIA',
	MERCEDES = 'MERCEDES',
	TOYOTA = 'TOYOTA',
	AUDI = 'AUDI',
	VOLKSWAGEN = 'VOLKSWAGEN',
	LEXUS = 'LEXUS',
	MOTORCYCLE = 'MOTORCYCLE',
  CADILLAC = 'CADILLAC',
	OTHERS = 'OTHERS',
}

export enum PropertyStatus {
	ACTIVE = 'ACTIVE',
	SOLD = 'SOLD',
	DELETE = 'DELETE',
}

export enum PropertyTypes {
	ECONOM = 'ECONOM',
	COMPACT = 'COMPACT',
	MIDSIZE = 'MIDSIZE',
	STANDARD = 'STANDARD',
	FULLSIZE = 'FULLSIZE',
	REMUMP = 'REMUMP ',
	LUXURY = 'LUXURY',
	VAN = 'VAN',
	SPORTURILITY = 'SPORTURILITY',
	CONVERTIBLE = 'CONVERTIBLE',
}
